import Biodata1111Img from "../assets/biodata/biodata-1111.png";
import Biodata1112Img from "../assets/biodata/biodata-1112.png";
import Biodata1113Img from "../assets/biodata/biodata-1113.png";
import Biodata1118Img from "../assets/biodata/biodata-1118.png";
import Languages from "../json/Languages";
import ModelTypes from "../json/ModelTypes";

const biodataList = [
  {
    id: 1,
    modelNumber: "1111",
    image: Biodata1111Img,
    hindiImage: "/images/hindi-professional.jpg",
    studentImage: Biodata1111Img,
    hindiStudentImage: "/images/hindi-student.jpg",
    originalPrice: 201,
    discountedPrice: 101,
    discount: 50,
    title: "Madhubani Painting",
    modelName: "madhubani-painting",
    description:
      "Madhubani painting is a traditional Indian art form that originated in the Mithila region of Bihar. It is characterized by intricate patterns, vibrant colors, and themes from mythology, nature, and daily life. The paintings are typically done on handmade paper or cloth using natural dyes and pigments. Madhubani artists often use fine brushes made from twigs or fingers to create detailed designs. This art form has gained recognition worldwide for its unique style and cultural significance.",
    language: Languages.English.Name,
    type: ModelTypes.Professional.Name,
  },
  {
    id: 2,
    modelNumber: "1112",
    image: Biodata1112Img,
    hindiImage: "/images/hindi-professional.jpg",
    studentImage: Biodata1112Img,
    hindiStudentImage: "/images/hindi-student.jpg",
    originalPrice: 201,
    discountedPrice: 101,
    discount: 50,
    title: "Madhubani Oily",
    modelName: "madhubani-oiy",
    description:
      "Madhubani painting is a traditional Indian art form that originated in the Mithila region of Bihar. It is characterized by intricate patterns, vibrant colors, and themes from mythology, nature, and daily life. The paintings are typically done on handmade paper or cloth using natural dyes and pigments. Madhubani artists often use fine brushes made from twigs or fingers to create detailed designs. This art form has gained recognition worldwide for its unique style and cultural significance.",
    language: Languages.English.Name,
    type: ModelTypes.Professional.Name,
  },
  {
    id: 3,
    modelNumber: "1113",
    image: Biodata1113Img,
    hindiImage: "/images/hindi-professional.jpg",
    studentImage: Biodata1113Img,
    hindiStudentImage: "/images/hindi-student.jpg",
    originalPrice: 201,
    discountedPrice: 101,
    discount: 50,
    title: "Madhubani Painting",
    modelName: "madhubani-painting-3",
    description:
      "Madhubani painting is a traditional Indian art form that originated in the Mithila region of Bihar. It is characterized by intricate patterns, vibrant colors, and themes from mythology, nature, and daily life. The paintings are typically done on handmade paper or cloth using natural dyes and pigments. Madhubani artists often use fine brushes made from twigs or fingers to create detailed designs. This art form has gained recognition worldwide for its unique style and cultural significance.",
    language: Languages.English.Name,
    type: ModelTypes.Professional.Name,
  },
  {
    id: 4,
    modelNumber: "1114",
    image: Biodata1111Img,
    hindiImage: "/images/hindi-professional.jpg",
    studentImage: Biodata1111Img,
    hindiStudentImage: "/images/hindi-student.jpg",
    originalPrice: 201,
    discountedPrice: 101,
    discount: 50,
    title: "Madhubani Painting",
    modelName: "madhubani-painting-4",
    description:
      "Madhubani painting is a traditional Indian art form that originated in the Mithila region of Bihar. It is characterized by intricate patterns, vibrant colors, and themes from mythology, nature, and daily life. The paintings are typically done on handmade paper or cloth using natural dyes and pigments. Madhubani artists often use fine brushes made from twigs or fingers to create detailed designs. This art form has gained recognition worldwide for its unique style and cultural significance.",
    language: Languages.English.Name,
    type: ModelTypes.Professional.Name,
  },
  {
    id: 5,
    modelNumber: "1115",
    image: Biodata1111Img,
    hindiImage: "/images/hindi-professional.jpg",
    studentImage: Biodata1111Img,
    hindiStudentImage: "/images/hindi-student.jpg",
    originalPrice: 201,
    discountedPrice: 101,
    discount: 50,
    title: "Madhubani Painting",
    modelName: "madhubani-painting-5",
    description:
      "Madhubani painting is a traditional Indian art form that originated in the Mithila region of Bihar. It is characterized by intricate patterns, vibrant colors, and themes from mythology, nature, and daily life. The paintings are typically done on handmade paper or cloth using natural dyes and pigments. Madhubani artists often use fine brushes made from twigs or fingers to create detailed designs. This art form has gained recognition worldwide for its unique style and cultural significance.",
    language: Languages.English.Name,
    type: ModelTypes.Professional.Name,
  },
  {
    id: 6,
    modelNumber: "1116",
    image: Biodata1111Img,
    hindiImage: "/images/hindi-professional.jpg",
    studentImage: Biodata1111Img,
    hindiStudentImage: "/images/hindi-student.jpg",
    originalPrice: 201,
    discountedPrice: 101,
    discount: 50,
    title: "Madhubani Painting",
    modelName: "madhubani-painting-6",
    description:
      "Madhubani painting is a traditional Indian art form that originated in the Mithila region of Bihar. It is characterized by intricate patterns, vibrant colors, and themes from mythology, nature, and daily life. The paintings are typically done on handmade paper or cloth using natural dyes and pigments. Madhubani artists often use fine brushes made from twigs or fingers to create detailed designs. This art form has gained recognition worldwide for its unique style and cultural significance.",
    language: Languages.English.Name,
    type: ModelTypes.Professional.Name,
  },
    {
    id: 7,
    modelNumber: "1117",
    image: Biodata1111Img,
    hindiImage: "/images/hindi-professional.jpg",
    studentImage: Biodata1111Img,
    hindiStudentImage: "/images/hindi-student.jpg",
    originalPrice: 201,
    discountedPrice: 101,
    discount: 50,
    title: "Madhubani Painting",
    modelName: "madhubani-painting-6",
    description:
      "Madhubani painting is a traditional Indian art form that originated in the Mithila region of Bihar. It is characterized by intricate patterns, vibrant colors, and themes from mythology, nature, and daily life. The paintings are typically done on handmade paper or cloth using natural dyes and pigments. Madhubani artists often use fine brushes made from twigs or fingers to create detailed designs. This art form has gained recognition worldwide for its unique style and cultural significance.",
    language: Languages.English.Name,
    type: ModelTypes.Professional.Name,
  },
    {
    id: 8,
    modelNumber: "1118",
    image: Biodata1118Img,
    hindiImage: "/images/hindi-professional.jpg",
    studentImage: Biodata1118Img,
    hindiStudentImage: "/images/hindi-student.jpg",
    originalPrice: 201,
    discountedPrice: 101,
    discount: 50,
    title: "Madhubani Painting",
    modelName: "madhubani-painting-6",
    description:
      "Madhubani painting is a traditional Indian art form that originated in the Mithila region of Bihar. It is characterized by intricate patterns, vibrant colors, and themes from mythology, nature, and daily life. The paintings are typically done on handmade paper or cloth using natural dyes and pigments. Madhubani artists often use fine brushes made from twigs or fingers to create detailed designs. This art form has gained recognition worldwide for its unique style and cultural significance.",
    language: Languages.English.Name,
    type: ModelTypes.Professional.Name,
  },
];

export default biodataList;
